// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v7.36.1
// source: xas.proto

package v1alpha

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	XASServer_UpdatePolicy_FullMethodName           = "/xas.v1alpha.XASServer/UpdatePolicy"
	XASServer_DeletePolicy_FullMethodName           = "/xas.v1alpha.XASServer/DeletePolicy"
	XASServer_ListPolicies_FullMethodName           = "/xas.v1alpha.XASServer/ListPolicies"
	XASServer_UpdateWorkload_FullMethodName         = "/xas.v1alpha.XASServer/UpdateWorkload"
	XASServer_GetControlMetrics_FullMethodName      = "/xas.v1alpha.XASServer/GetControlMetrics"
	XASServer_UpdateRecommenderState_FullMethodName = "/xas.v1alpha.XASServer/UpdateRecommenderState"
	XASServer_GetRecommendation_FullMethodName      = "/xas.v1alpha.XASServer/GetRecommendation"
	XASServer_IngestMetrics_FullMethodName          = "/xas.v1alpha.XASServer/IngestMetrics"
)

// XASServerClient is the client API for XASServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// XASServer defines the gRPC interface for the XAS Server.
// It acts as the central state manager for autoscaling policies, workload state,
// metric ingestion, and decision making.
type XASServerClient interface {
	// --- Policy Management ---
	// Create or Update a ScalingPolicy. This is an idempotent "Upsert".
	UpdatePolicy(ctx context.Context, in *UpdatePolicyRequest, opts ...grpc.CallOption) (*Policy, error)
	// Delete a ScalingPolicy.
	DeletePolicy(ctx context.Context, in *DeletePolicyRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// List all known policies, optionally filtered by cluster.
	ListPolicies(ctx context.Context, in *ListPoliciesRequest, opts ...grpc.CallOption) (*ListPoliciesResponse, error)
	// --- Workload Management (Controller -> Server) ---
	// Update the Server's view of the workload (Pods) for a specific policy.
	// This is a full replacement of the pod list.
	// TODO(): This method should probably just return an empty response (google.protobuf.Empty).
	UpdateWorkload(ctx context.Context, in *UpdateWorkloadRequest, opts ...grpc.CallOption) (*Workload, error)
	// --- Control Metrics (Recommender -> Server) ---
	// Read the current aggregated metric values ("Control Metrics") for a policy.
	// Recommenders use this to compute their recommendations.
	GetControlMetrics(ctx context.Context, in *GetControlMetricsRequest, opts ...grpc.CallOption) (*ControlMetrics, error)
	// --- Recommender State (Plugin -> Server) ---
	// Update the status (recommendation) of a specific recommender.
	// Recommenders push their calculated recommendation here.
	UpdateRecommenderState(ctx context.Context, in *UpdateRecommenderStateRequest, opts ...grpc.CallOption) (*RecommenderState, error)
	// --- Recommendation (Controller -> Server) ---
	// Retrieve the final arbitrated recommendation for a policy.
	// The Controller uses this to scale the target workload.
	GetRecommendation(ctx context.Context, in *GetRecommendationRequest, opts ...grpc.CallOption) (*GetRecommendationResponse, error)
	// --- Ingestion (Agent -> Server) ---
	// Push raw metric samples from an Agent (Node).
	IngestMetrics(ctx context.Context, in *IngestMetricsRequest, opts ...grpc.CallOption) (*IngestMetricsResponse, error)
}

type xASServerClient struct {
	cc grpc.ClientConnInterface
}

func NewXASServerClient(cc grpc.ClientConnInterface) XASServerClient {
	return &xASServerClient{cc}
}

func (c *xASServerClient) UpdatePolicy(ctx context.Context, in *UpdatePolicyRequest, opts ...grpc.CallOption) (*Policy, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Policy)
	err := c.cc.Invoke(ctx, XASServer_UpdatePolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *xASServerClient) DeletePolicy(ctx context.Context, in *DeletePolicyRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, XASServer_DeletePolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *xASServerClient) ListPolicies(ctx context.Context, in *ListPoliciesRequest, opts ...grpc.CallOption) (*ListPoliciesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPoliciesResponse)
	err := c.cc.Invoke(ctx, XASServer_ListPolicies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *xASServerClient) UpdateWorkload(ctx context.Context, in *UpdateWorkloadRequest, opts ...grpc.CallOption) (*Workload, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Workload)
	err := c.cc.Invoke(ctx, XASServer_UpdateWorkload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *xASServerClient) GetControlMetrics(ctx context.Context, in *GetControlMetricsRequest, opts ...grpc.CallOption) (*ControlMetrics, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ControlMetrics)
	err := c.cc.Invoke(ctx, XASServer_GetControlMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *xASServerClient) UpdateRecommenderState(ctx context.Context, in *UpdateRecommenderStateRequest, opts ...grpc.CallOption) (*RecommenderState, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecommenderState)
	err := c.cc.Invoke(ctx, XASServer_UpdateRecommenderState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *xASServerClient) GetRecommendation(ctx context.Context, in *GetRecommendationRequest, opts ...grpc.CallOption) (*GetRecommendationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRecommendationResponse)
	err := c.cc.Invoke(ctx, XASServer_GetRecommendation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *xASServerClient) IngestMetrics(ctx context.Context, in *IngestMetricsRequest, opts ...grpc.CallOption) (*IngestMetricsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IngestMetricsResponse)
	err := c.cc.Invoke(ctx, XASServer_IngestMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// XASServerServer is the server API for XASServer service.
// All implementations must embed UnimplementedXASServerServer
// for forward compatibility.
//
// XASServer defines the gRPC interface for the XAS Server.
// It acts as the central state manager for autoscaling policies, workload state,
// metric ingestion, and decision making.
type XASServerServer interface {
	// --- Policy Management ---
	// Create or Update a ScalingPolicy. This is an idempotent "Upsert".
	UpdatePolicy(context.Context, *UpdatePolicyRequest) (*Policy, error)
	// Delete a ScalingPolicy.
	DeletePolicy(context.Context, *DeletePolicyRequest) (*emptypb.Empty, error)
	// List all known policies, optionally filtered by cluster.
	ListPolicies(context.Context, *ListPoliciesRequest) (*ListPoliciesResponse, error)
	// --- Workload Management (Controller -> Server) ---
	// Update the Server's view of the workload (Pods) for a specific policy.
	// This is a full replacement of the pod list.
	// TODO(): This method should probably just return an empty response (google.protobuf.Empty).
	UpdateWorkload(context.Context, *UpdateWorkloadRequest) (*Workload, error)
	// --- Control Metrics (Recommender -> Server) ---
	// Read the current aggregated metric values ("Control Metrics") for a policy.
	// Recommenders use this to compute their recommendations.
	GetControlMetrics(context.Context, *GetControlMetricsRequest) (*ControlMetrics, error)
	// --- Recommender State (Plugin -> Server) ---
	// Update the status (recommendation) of a specific recommender.
	// Recommenders push their calculated recommendation here.
	UpdateRecommenderState(context.Context, *UpdateRecommenderStateRequest) (*RecommenderState, error)
	// --- Recommendation (Controller -> Server) ---
	// Retrieve the final arbitrated recommendation for a policy.
	// The Controller uses this to scale the target workload.
	GetRecommendation(context.Context, *GetRecommendationRequest) (*GetRecommendationResponse, error)
	// --- Ingestion (Agent -> Server) ---
	// Push raw metric samples from an Agent (Node).
	IngestMetrics(context.Context, *IngestMetricsRequest) (*IngestMetricsResponse, error)
	mustEmbedUnimplementedXASServerServer()
}

// UnimplementedXASServerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedXASServerServer struct{}

func (UnimplementedXASServerServer) UpdatePolicy(context.Context, *UpdatePolicyRequest) (*Policy, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdatePolicy not implemented")
}
func (UnimplementedXASServerServer) DeletePolicy(context.Context, *DeletePolicyRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeletePolicy not implemented")
}
func (UnimplementedXASServerServer) ListPolicies(context.Context, *ListPoliciesRequest) (*ListPoliciesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPolicies not implemented")
}
func (UnimplementedXASServerServer) UpdateWorkload(context.Context, *UpdateWorkloadRequest) (*Workload, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateWorkload not implemented")
}
func (UnimplementedXASServerServer) GetControlMetrics(context.Context, *GetControlMetricsRequest) (*ControlMetrics, error) {
	return nil, status.Error(codes.Unimplemented, "method GetControlMetrics not implemented")
}
func (UnimplementedXASServerServer) UpdateRecommenderState(context.Context, *UpdateRecommenderStateRequest) (*RecommenderState, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateRecommenderState not implemented")
}
func (UnimplementedXASServerServer) GetRecommendation(context.Context, *GetRecommendationRequest) (*GetRecommendationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRecommendation not implemented")
}
func (UnimplementedXASServerServer) IngestMetrics(context.Context, *IngestMetricsRequest) (*IngestMetricsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IngestMetrics not implemented")
}
func (UnimplementedXASServerServer) mustEmbedUnimplementedXASServerServer() {}
func (UnimplementedXASServerServer) testEmbeddedByValue()                   {}

// UnsafeXASServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to XASServerServer will
// result in compilation errors.
type UnsafeXASServerServer interface {
	mustEmbedUnimplementedXASServerServer()
}

func RegisterXASServerServer(s grpc.ServiceRegistrar, srv XASServerServer) {
	// If the following call panics, it indicates UnimplementedXASServerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&XASServer_ServiceDesc, srv)
}

func _XASServer_UpdatePolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XASServerServer).UpdatePolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: XASServer_UpdatePolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XASServerServer).UpdatePolicy(ctx, req.(*UpdatePolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _XASServer_DeletePolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XASServerServer).DeletePolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: XASServer_DeletePolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XASServerServer).DeletePolicy(ctx, req.(*DeletePolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _XASServer_ListPolicies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPoliciesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XASServerServer).ListPolicies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: XASServer_ListPolicies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XASServerServer).ListPolicies(ctx, req.(*ListPoliciesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _XASServer_UpdateWorkload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateWorkloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XASServerServer).UpdateWorkload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: XASServer_UpdateWorkload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XASServerServer).UpdateWorkload(ctx, req.(*UpdateWorkloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _XASServer_GetControlMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetControlMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XASServerServer).GetControlMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: XASServer_GetControlMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XASServerServer).GetControlMetrics(ctx, req.(*GetControlMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _XASServer_UpdateRecommenderState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRecommenderStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XASServerServer).UpdateRecommenderState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: XASServer_UpdateRecommenderState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XASServerServer).UpdateRecommenderState(ctx, req.(*UpdateRecommenderStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _XASServer_GetRecommendation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRecommendationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XASServerServer).GetRecommendation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: XASServer_GetRecommendation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XASServerServer).GetRecommendation(ctx, req.(*GetRecommendationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _XASServer_IngestMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IngestMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XASServerServer).IngestMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: XASServer_IngestMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XASServerServer).IngestMetrics(ctx, req.(*IngestMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// XASServer_ServiceDesc is the grpc.ServiceDesc for XASServer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var XASServer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "xas.v1alpha.XASServer",
	HandlerType: (*XASServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdatePolicy",
			Handler:    _XASServer_UpdatePolicy_Handler,
		},
		{
			MethodName: "DeletePolicy",
			Handler:    _XASServer_DeletePolicy_Handler,
		},
		{
			MethodName: "ListPolicies",
			Handler:    _XASServer_ListPolicies_Handler,
		},
		{
			MethodName: "UpdateWorkload",
			Handler:    _XASServer_UpdateWorkload_Handler,
		},
		{
			MethodName: "GetControlMetrics",
			Handler:    _XASServer_GetControlMetrics_Handler,
		},
		{
			MethodName: "UpdateRecommenderState",
			Handler:    _XASServer_UpdateRecommenderState_Handler,
		},
		{
			MethodName: "GetRecommendation",
			Handler:    _XASServer_GetRecommendation_Handler,
		},
		{
			MethodName: "IngestMetrics",
			Handler:    _XASServer_IngestMetrics_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "xas.proto",
}
