#!/bin/bash
set -e

ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/.."

HOOK_DIR="$ROOT/.git/hooks"
HOOK_FILE="$HOOK_DIR/pre-commit"

if [ ! -d "$ROOT/.git" ]; then
    echo "Error: Not a git repository root."
    exit 1
fi

echo "Installing pre-commit hook..."

cat > "$HOOK_FILE" <<EOF
#!/bin/sh
# Auto-generated by hack/install-hooks.sh
exec 1>&2
echo "Running pre-commit checks (hack/verify.sh)..."
./hack/verify.sh
EOF

chmod +x "$HOOK_FILE"

echo "Hook installed at $HOOK_FILE"
