/*
Copyright 2024 The XAS Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	xasv1 "github.com/gke-labs/extensible-workload-autoscaler/pkg/apis/xas/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// MetricProviderClassLister helps list MetricProviderClasses.
// All objects returned here must be treated as read-only.
type MetricProviderClassLister interface {
	// List lists all MetricProviderClasses in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*xasv1.MetricProviderClass, err error)
	// Get retrieves the MetricProviderClass from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*xasv1.MetricProviderClass, error)
	MetricProviderClassListerExpansion
}

// metricProviderClassLister implements the MetricProviderClassLister interface.
type metricProviderClassLister struct {
	listers.ResourceIndexer[*xasv1.MetricProviderClass]
}

// NewMetricProviderClassLister returns a new MetricProviderClassLister.
func NewMetricProviderClassLister(indexer cache.Indexer) MetricProviderClassLister {
	return &metricProviderClassLister{listers.New[*xasv1.MetricProviderClass](indexer, xasv1.Resource("metricproviderclass"))}
}
