/*
Copyright 2024 The XAS Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	xasv1 "github.com/gke-labs/extensible-workload-autoscaler/pkg/apis/xas/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// RecommenderClassLister helps list RecommenderClasses.
// All objects returned here must be treated as read-only.
type RecommenderClassLister interface {
	// List lists all RecommenderClasses in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*xasv1.RecommenderClass, err error)
	// Get retrieves the RecommenderClass from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*xasv1.RecommenderClass, error)
	RecommenderClassListerExpansion
}

// recommenderClassLister implements the RecommenderClassLister interface.
type recommenderClassLister struct {
	listers.ResourceIndexer[*xasv1.RecommenderClass]
}

// NewRecommenderClassLister returns a new RecommenderClassLister.
func NewRecommenderClassLister(indexer cache.Indexer) RecommenderClassLister {
	return &recommenderClassLister{listers.New[*xasv1.RecommenderClass](indexer, xasv1.Resource("recommenderclass"))}
}
