/*
Copyright 2024 The XAS Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	xasv1 "github.com/gke-labs/extensible-workload-autoscaler/pkg/apis/xas/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// ScalingPolicyLister helps list ScalingPolicies.
// All objects returned here must be treated as read-only.
type ScalingPolicyLister interface {
	// List lists all ScalingPolicies in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*xasv1.ScalingPolicy, err error)
	// ScalingPolicies returns an object that can list and get ScalingPolicies.
	ScalingPolicies(namespace string) ScalingPolicyNamespaceLister
	ScalingPolicyListerExpansion
}

// scalingPolicyLister implements the ScalingPolicyLister interface.
type scalingPolicyLister struct {
	listers.ResourceIndexer[*xasv1.ScalingPolicy]
}

// NewScalingPolicyLister returns a new ScalingPolicyLister.
func NewScalingPolicyLister(indexer cache.Indexer) ScalingPolicyLister {
	return &scalingPolicyLister{listers.New[*xasv1.ScalingPolicy](indexer, xasv1.Resource("scalingpolicy"))}
}

// ScalingPolicies returns an object that can list and get ScalingPolicies.
func (s *scalingPolicyLister) ScalingPolicies(namespace string) ScalingPolicyNamespaceLister {
	return scalingPolicyNamespaceLister{listers.NewNamespaced[*xasv1.ScalingPolicy](s.ResourceIndexer, namespace)}
}

// ScalingPolicyNamespaceLister helps list and get ScalingPolicies.
// All objects returned here must be treated as read-only.
type ScalingPolicyNamespaceLister interface {
	// List lists all ScalingPolicies in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*xasv1.ScalingPolicy, err error)
	// Get retrieves the ScalingPolicy from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*xasv1.ScalingPolicy, error)
	ScalingPolicyNamespaceListerExpansion
}

// scalingPolicyNamespaceLister implements the ScalingPolicyNamespaceLister
// interface.
type scalingPolicyNamespaceLister struct {
	listers.ResourceIndexer[*xasv1.ScalingPolicy]
}
