/*
Copyright 2024 The XAS Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	context "context"
	time "time"

	apisxasv1 "github.com/gke-labs/extensible-workload-autoscaler/pkg/apis/xas/v1"
	versioned "github.com/gke-labs/extensible-workload-autoscaler/pkg/client/clientset/versioned"
	internalinterfaces "github.com/gke-labs/extensible-workload-autoscaler/pkg/client/informers/externalversions/internalinterfaces"
	xasv1 "github.com/gke-labs/extensible-workload-autoscaler/pkg/client/listers/xas/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// RecommenderClassInformer provides access to a shared informer and lister for
// RecommenderClasses.
type RecommenderClassInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() xasv1.RecommenderClassLister
}

type recommenderClassInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewRecommenderClassInformer constructs a new informer for RecommenderClass type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewRecommenderClassInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredRecommenderClassInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredRecommenderClassInformer constructs a new informer for RecommenderClass type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredRecommenderClassInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		cache.ToListWatcherWithWatchListSemantics(&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.XasV1().RecommenderClasses().List(context.Background(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.XasV1().RecommenderClasses().Watch(context.Background(), options)
			},
			ListWithContextFunc: func(ctx context.Context, options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.XasV1().RecommenderClasses().List(ctx, options)
			},
			WatchFuncWithContext: func(ctx context.Context, options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.XasV1().RecommenderClasses().Watch(ctx, options)
			},
		}, client),
		&apisxasv1.RecommenderClass{},
		resyncPeriod,
		indexers,
	)
}

func (f *recommenderClassInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredRecommenderClassInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *recommenderClassInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apisxasv1.RecommenderClass{}, f.defaultInformer)
}

func (f *recommenderClassInformer) Lister() xasv1.RecommenderClassLister {
	return xasv1.NewRecommenderClassLister(f.Informer().GetIndexer())
}
