apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: xas-control-plane
  namespace: xas-system
spec:
  selector:
    matchLabels:
      app: xas-server
  endpoints:
  - port: 9090
    path: /metrics
    interval: 30s
