/*
Copyright 2024 The XAS Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/gke-labs/extensible-workload-autoscaler/pkg/apis/xas/v1"
	xasv1 "github.com/gke-labs/extensible-workload-autoscaler/pkg/client/clientset/versioned/typed/xas/v1"
	gentype "k8s.io/client-go/gentype"
)

// fakeScalingPolicies implements ScalingPolicyInterface
type fakeScalingPolicies struct {
	*gentype.FakeClientWithList[*v1.ScalingPolicy, *v1.ScalingPolicyList]
	Fake *FakeXasV1
}

func newFakeScalingPolicies(fake *FakeXasV1, namespace string) xasv1.ScalingPolicyInterface {
	return &fakeScalingPolicies{
		gentype.NewFakeClientWithList[*v1.ScalingPolicy, *v1.ScalingPolicyList](
			fake.Fake,
			namespace,
			v1.SchemeGroupVersion.WithResource("scalingpolicies"),
			v1.SchemeGroupVersion.WithKind("ScalingPolicy"),
			func() *v1.ScalingPolicy { return &v1.ScalingPolicy{} },
			func() *v1.ScalingPolicyList { return &v1.ScalingPolicyList{} },
			func(dst, src *v1.ScalingPolicyList) { dst.ListMeta = src.ListMeta },
			func(list *v1.ScalingPolicyList) []*v1.ScalingPolicy { return gentype.ToPointerSlice(list.Items) },
			func(list *v1.ScalingPolicyList, items []*v1.ScalingPolicy) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
