/*
Copyright 2024 The XAS Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	context "context"

	xasv1 "github.com/gke-labs/extensible-workload-autoscaler/pkg/apis/xas/v1"
	scheme "github.com/gke-labs/extensible-workload-autoscaler/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// RecommenderClassesGetter has a method to return a RecommenderClassInterface.
// A group's client should implement this interface.
type RecommenderClassesGetter interface {
	RecommenderClasses() RecommenderClassInterface
}

// RecommenderClassInterface has methods to work with RecommenderClass resources.
type RecommenderClassInterface interface {
	Create(ctx context.Context, recommenderClass *xasv1.RecommenderClass, opts metav1.CreateOptions) (*xasv1.RecommenderClass, error)
	Update(ctx context.Context, recommenderClass *xasv1.RecommenderClass, opts metav1.UpdateOptions) (*xasv1.RecommenderClass, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*xasv1.RecommenderClass, error)
	List(ctx context.Context, opts metav1.ListOptions) (*xasv1.RecommenderClassList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *xasv1.RecommenderClass, err error)
	RecommenderClassExpansion
}

// recommenderClasses implements RecommenderClassInterface
type recommenderClasses struct {
	*gentype.ClientWithList[*xasv1.RecommenderClass, *xasv1.RecommenderClassList]
}

// newRecommenderClasses returns a RecommenderClasses
func newRecommenderClasses(c *XasV1Client) *recommenderClasses {
	return &recommenderClasses{
		gentype.NewClientWithList[*xasv1.RecommenderClass, *xasv1.RecommenderClassList](
			"recommenderclasses",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *xasv1.RecommenderClass { return &xasv1.RecommenderClass{} },
			func() *xasv1.RecommenderClassList { return &xasv1.RecommenderClassList{} },
		),
	}
}
