/*
Copyright 2024 The XAS Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	context "context"

	xasv1 "github.com/gke-labs/extensible-workload-autoscaler/pkg/apis/xas/v1"
	scheme "github.com/gke-labs/extensible-workload-autoscaler/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// ScalingPoliciesGetter has a method to return a ScalingPolicyInterface.
// A group's client should implement this interface.
type ScalingPoliciesGetter interface {
	ScalingPolicies(namespace string) ScalingPolicyInterface
}

// ScalingPolicyInterface has methods to work with ScalingPolicy resources.
type ScalingPolicyInterface interface {
	Create(ctx context.Context, scalingPolicy *xasv1.ScalingPolicy, opts metav1.CreateOptions) (*xasv1.ScalingPolicy, error)
	Update(ctx context.Context, scalingPolicy *xasv1.ScalingPolicy, opts metav1.UpdateOptions) (*xasv1.ScalingPolicy, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, scalingPolicy *xasv1.ScalingPolicy, opts metav1.UpdateOptions) (*xasv1.ScalingPolicy, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*xasv1.ScalingPolicy, error)
	List(ctx context.Context, opts metav1.ListOptions) (*xasv1.ScalingPolicyList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *xasv1.ScalingPolicy, err error)
	ScalingPolicyExpansion
}

// scalingPolicies implements ScalingPolicyInterface
type scalingPolicies struct {
	*gentype.ClientWithList[*xasv1.ScalingPolicy, *xasv1.ScalingPolicyList]
}

// newScalingPolicies returns a ScalingPolicies
func newScalingPolicies(c *XasV1Client, namespace string) *scalingPolicies {
	return &scalingPolicies{
		gentype.NewClientWithList[*xasv1.ScalingPolicy, *xasv1.ScalingPolicyList](
			"scalingpolicies",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *xasv1.ScalingPolicy { return &xasv1.ScalingPolicy{} },
			func() *xasv1.ScalingPolicyList { return &xasv1.ScalingPolicyList{} },
		),
	}
}
