/*
Copyright 2024 The XAS Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	http "net/http"

	xasv1 "github.com/gke-labs/extensible-workload-autoscaler/pkg/apis/xas/v1"
	scheme "github.com/gke-labs/extensible-workload-autoscaler/pkg/client/clientset/versioned/scheme"
	rest "k8s.io/client-go/rest"
)

type XasV1Interface interface {
	RESTClient() rest.Interface
	MetricProviderClassesGetter
	RecommenderClassesGetter
	ScalingPoliciesGetter
}

// XasV1Client is used to interact with features provided by the xas.io group.
type XasV1Client struct {
	restClient rest.Interface
}

func (c *XasV1Client) MetricProviderClasses() MetricProviderClassInterface {
	return newMetricProviderClasses(c)
}

func (c *XasV1Client) RecommenderClasses() RecommenderClassInterface {
	return newRecommenderClasses(c)
}

func (c *XasV1Client) ScalingPolicies(namespace string) ScalingPolicyInterface {
	return newScalingPolicies(c, namespace)
}

// NewForConfig creates a new XasV1Client for the given config.
// NewForConfig is equivalent to NewForConfigAndClient(c, httpClient),
// where httpClient was generated with rest.HTTPClientFor(c).
func NewForConfig(c *rest.Config) (*XasV1Client, error) {
	config := *c
	setConfigDefaults(&config)
	httpClient, err := rest.HTTPClientFor(&config)
	if err != nil {
		return nil, err
	}
	return NewForConfigAndClient(&config, httpClient)
}

// NewForConfigAndClient creates a new XasV1Client for the given config and http client.
// Note the http client provided takes precedence over the configured transport values.
func NewForConfigAndClient(c *rest.Config, h *http.Client) (*XasV1Client, error) {
	config := *c
	setConfigDefaults(&config)
	client, err := rest.RESTClientForConfigAndClient(&config, h)
	if err != nil {
		return nil, err
	}
	return &XasV1Client{client}, nil
}

// NewForConfigOrDie creates a new XasV1Client for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *XasV1Client {
	client, err := NewForConfig(c)
	if err != nil {
		panic(err)
	}
	return client
}

// New creates a new XasV1Client for the given RESTClient.
func New(c rest.Interface) *XasV1Client {
	return &XasV1Client{c}
}

func setConfigDefaults(config *rest.Config) {
	gv := xasv1.SchemeGroupVersion
	config.GroupVersion = &gv
	config.APIPath = "/apis"
	config.NegotiatedSerializer = rest.CodecFactoryForGeneratedClient(scheme.Scheme, scheme.Codecs).WithoutConversion()

	if config.UserAgent == "" {
		config.UserAgent = rest.DefaultKubernetesUserAgent()
	}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *XasV1Client) RESTClient() rest.Interface {
	if c == nil {
		return nil
	}
	return c.restClient
}
